name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-2019
 
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install Dependencies
      run: |
        pip --disable-pip-version-check install pylama pylint pytest Cython
        pip --disable-pip-version-check install -r requirements.txt
    - name: Run Linter
      run: |
        pylama assets/scripts/libs/utm_agent/
    # - name: Run Tests
    #   run: |
    #     pytest
